// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8PLfcfssTNEVOwNsZASd9-74Zu4FZ-sU',
    appId: '1:753202558730:web:20d92252b0f4033666ecf3',
    messagingSenderId: '753202558730',
    projectId: 'vagavision-13295',
    authDomain: 'vagavision-13295.firebaseapp.com',
    storageBucket: 'vagavision-13295.firebasestorage.app',
    measurementId: 'G-H9L5VXX942',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KLJTdJvEHPjFBLB9pMvY3D1kRAVkVEE',
    appId: '1:753202558730:android:8723ca0856a3ece966ecf3',
    messagingSenderId: '753202558730',
    projectId: 'vagavision-13295',
    storageBucket: 'vagavision-13295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAloBumb-Ke_t1BG1gq20Rywc8-SdUQA5Q',
    appId: '1:753202558730:ios:bf6da8c3004d1b7b66ecf3',
    messagingSenderId: '753202558730',
    projectId: 'vagavision-13295',
    storageBucket: 'vagavision-13295.firebasestorage.app',
    iosBundleId: 'br.maua.garagemCentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAloBumb-Ke_t1BG1gq20Rywc8-SdUQA5Q',
    appId: '1:753202558730:ios:bf6da8c3004d1b7b66ecf3',
    messagingSenderId: '753202558730',
    projectId: 'vagavision-13295',
    storageBucket: 'vagavision-13295.firebasestorage.app',
    iosBundleId: 'br.maua.garagemCentral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8PLfcfssTNEVOwNsZASd9-74Zu4FZ-sU',
    appId: '1:753202558730:web:5625ed03cab7479c66ecf3',
    messagingSenderId: '753202558730',
    projectId: 'vagavision-13295',
    authDomain: 'vagavision-13295.firebaseapp.com',
    storageBucket: 'vagavision-13295.firebasestorage.app',
    measurementId: 'G-519V7Z0SXT',
  );
}
